### ISSUE TITLE
dependency issue when building

### ISSUE THREAD

**Issue by johandoornenbal** [isisaddons/isis-app-kitchensink#2]
[ERROR]   The project org.isisaddons.app.kitchensink:isis-app-kitchensink-webapp:1.14.0-SNAPSHOT (/Users/jodo/src/isis-app-kitchensink/webapp/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.apache.isis.viewer:isis-viewer-wicket-impl:jar is missing. @ org.isisaddons.app.kitchensink:isis-app-kitchensink-webapp:[unknown-version], /Users/jodo/src/isis-app-kitchensink/webapp/pom.xml, line 80, column 21

**Comment by danhaywood** [comment]
OK, I've created a branch to solve this.

On github.com/apache/isis, the "maint-1.14.0" branch holds 1.14.0-SNAPSHOT.
Corresponds to "master" in this repo.

On github.com/apache/isis, the "master" branch holds 1.15.0-SNAPSHOT.
Corresponds to "1.15.0" branch in this repo.

**Comment by danhaywood** [comment]
I've now created a maint-1.14.0 for 1.14.0, while master has been merged into 1.15.0 branch (for 1.15.0-SNAPSHOT development)
